import wshell

# PAYLOAD
DEFAULT_COMMAND_PLACEHOLDER = "WSHELL"

# HTTP
DEFAULT_TIMEOUT = 3.0
DEFAULT_DELAY = 0.0
DEFAULT_REUSE_CONNECTION = True
DEFAULT_ALLOW_REDIRECTS = True
DEFAULT_USER_AGENT = f"WShell v{wshell.VERSION}"
DEFAULT_USE_JSON_POST_DATA = False

# LOGGING
DEFAULT_LOG_LEVEL = "warning"